version: "2.4"
services:
  api:
    image: docker.io/isoxya/isoxya-api:unstable
    init: true
    networks:
      - api
      - processor
      - streamer
    ports:
      - 0.0.0.0:80:80
    restart: on-failure
  plugin_crawler_html:
    image: docker.io/isoxya/isoxya-plugin-crawler-html:unstable
    init: true
    networks:
      processor:
        aliases:
          - isoxya-plugin-crawler-html.localhost
    restart: on-failure
  nginx_test_upstream:
    image: docker.io/tiredpixel/nginx-test-upstream:latest
    networks:
      streamer:
        aliases:
          - nginx-test-upstream.localhost
    restart: on-failure
networks:
  api: {}
  processor: {}
  streamer: {}
