version: '2.4'
services:
  api:
    build:
      context: .
      target: builder
    init: true
    volumes:
      - .:/home/x/r
      - api_dist-newstyle:/home/x/r/dist-newstyle
    networks:
      - api
      - processor
      - streamer
    ports:
      - 0.0.0.0:80:80
    restart: on-failure
volumes:
  api_dist-newstyle: {}
networks:
  api: {}
  processor: {}
  streamer: {}
