version: '2.4'
services:
  api:
    build:
      context: .
      target: builder
    init: true
    volumes:
      - ./bin:/home/x/r/bin
      - ./cabal.project.freeze:/home/x/r/cabal.project.freeze
      - ./isoxya-api.cabal:/home/x/r/isoxya-api.cabal
      - ./lib:/home/x/r/lib
      - ./src:/home/x/r/src
      - ./test:/home/x/r/test
    networks:
      - api
      - processor
      - streamer
    ports:
      - 0.0.0.0:80:80
    restart: on-failure
networks:
  api: {}
  processor: {}
  streamer: {}
