version: "2.4"
services:
  api:
    image: docker.io/isoxya/isoxya-api:testing
    init: true
    volumes:
      - ./sqlite3.db:/home/x/sqlite3.db
    networks:
      - api
      - plugin
    ports:
      - 0.0.0.0:80:80
    restart: on-failure
  plugin_crawler_html:
    image: docker.io/isoxya/isoxya-plugin-crawler-html:testing
    init: true
    networks:
      plugin:
        aliases:
          - isoxya-plugin-crawler-html.localhost
    restart: on-failure
  nginx_test_upstream:
    image: docker.io/tiredpixel/nginx-test-upstream:latest
    networks:
      plugin:
        aliases:
          - nginx-test-upstream.localhost
    restart: on-failure
networks:
  api: {}
  plugin: {}
